project_id = "ubgpfhkwvntcavjbknxq"

[functions.send-login-notification]
verify_jwt = false

[functions.terminate-session]
verify_jwt = false

[functions.check-account-lockout]
verify_jwt = false

[functions.crypto-prices]
verify_jwt = false

[functions.check-liquidation]
verify_jwt = false
